version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: .docker/backend/Dockerfile
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/home/node/backend
    depends_on:
      - redis

  redis:
    image: redis:alpine
    expose:
      - "6379"